server:
  port: 8080
  servlet:
    context-path: /identity
    Content-Type: application/json
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: khang01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "jGTP5J6hVe05JjgGDOyU/r0PvxBihQyVIUj8RxKxisltktQ3TBzUS6lL3Ncd8lFs"
  valid-duration: 3600
  refreshable-duration: 360000